### ISSUE TITLE
Chocolatey package protonpass out of date - current protonpass version is 1.16.1

### ISSUE THREAD

**Issue by AIVAS001** [wadoli/chocolatey-pkg-protonpass#1]
Please update this package to reflect the current protonpass version of 1.16.1
https://proton.me/download/PassDesktop/win32/x64/ProtonPass_Setup_1.16.1.exe

**Comment by wadoli** [comment]
Thank you, I just pushed https://community.chocolatey.org/packages/protonpass/1.16.7
